### ISSUE TITLE
软件界面显示问题

### ISSUE THREAD

**Issue by falltree** [ZeroDeng01/SubconverterTools#2]
笔记本电脑，1080p屏幕
软件界面右侧显示只有一半，下方也显示不全，
右上角只有一个最小化按钮，没有最大化，四周也无法调节窗口大小。
下方的按钮全部都看不到，无法操作。
![image](https://github.com/user-attachments/assets/bd49922b-dfe7-4263-a902-333ed2d2c4a8)

另外，能否在主窗口，对本地的文件进行转换，比如有clash的config.yaml文件，转换为v2ray或其他。

**Comment by ZeroDeng01** [comment]
- 低分辨率显示不全的问题你使用0.0.8版本测试看看

**Comment by falltree** [comment]
> * 低分辨率显示不全的问题你使用0.0.8版本测试看看

下载了10月9日的0.0.8版本，
右侧界面的显示正常了，但下方还有几行无法显示，也无法改变窗口大小来调整。
另外，建议后端服务器可以自行手动输入来配置，比如我的后端是局域网IP:3000，输入后无法连接，似乎只能默认25500端口？
![image](https://github.com/user-attachments/assets/dd3cec54-69a0-46c3-b783-da36e52710b1)

**Comment by ZeroDeng01** [comment]
> > * 低分辨率显示不全的问题你使用0.0.8版本测试看看
> 
> 
> 
> 下载了10月9日的0.0.8版本，
> 
> 右侧界面的显示正常了，但下方还有几行无法显示，也无法改变窗口大小来调整。
> 
> 另外，建议后端服务器可以自行手动输入来配置，比如我的后端是局域网IP:3000，输入后无法连接，似乎只能默认25500端口？
> 
> ![image](https://github.com/user-attachments/assets/dd3cec54-69a0-46c3-b783-da36e52710b1)
> 
> 

你电脑是放大显示了吗?放大125% or 150%?

**Comment by ZeroDeng01** [comment]
![image](https://github.com/user-attachments/assets/0801cc83-af42-4840-866f-b37f3569ebd5)
已增加自定义后端功能 2249096

**Comment by falltree** [comment]
谢谢。确实是显示比例的问题，笔记本设置的是150%，0.0.8版显示不全，修改成125%后显示就完整了。只是125%字体太小。
现在换成0.0.10后，150%也能显示正常，自定义后端服务器也有了，问题圆满解决。

> > > * 低分辨率显示不全的问题你使用0.0.8版本测试看看
> > 
> > 
> > 下载了10月9日的0.0.8版本，
> > 右侧界面的显示正常了，但下方还有几行无法显示，也无法改变窗口大小来调整。
> > 另外，建议后端服务器可以自行手动输入来配置，比如我的后端是局域网IP:3000，输入后无法连接，似乎只能默认25500端口？
> > ![image](https://private-user-images.githubusercontent.com/38394738/376042971-dd3cec54-69a0-46c3-b783-da36e52710b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNzQzNzIsIm5iZiI6MTcyOTI3NDA3MiwicGF0aCI6Ii8zODM5NDczOC8zNzYwNDI5NzEtZGQzY2VjNTQtNjlhMC00NmMzLWI3ODMtZGEzNmU1MjcxMGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE3NTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0OWM1ZjZkMTExMTViZDIyNjBiYTYzYzlmZTQwYzQ1ZTVjMGZhMDljYzViMDdmNTVkNjVmMzBmYTAxNTc3MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-gbpFKe1XJ5Mnvi0xM-vsCfBDp2Tdyph4HiwqtcGqLY)
> 
> 你电脑是放大显示了吗?放大125% or 150%?

**Comment by ZeroDeng01** [comment]
> 谢谢。确实是显示比例的问题，笔记本设置的是150%，0.0.8版显示不全，修改成125%后显示就完整了。只是125%字体太小。
> 
> 现在换成0.0.10后，150%也能显示正常，自定义后端服务器也有了，问题圆满解决。
> 
> 
> 
> > > > * 低分辨率显示不全的问题你使用0.0.8版本测试看看
> 
> > > 
> 
> > > 
> 
> > > 下载了10月9日的0.0.8版本，
> 
> > > 右侧界面的显示正常了，但下方还有几行无法显示，也无法改变窗口大小来调整。
> 
> > > 另外，建议后端服务器可以自行手动输入来配置，比如我的后端是局域网IP:3000，输入后无法连接，似乎只能默认25500端口？
> 
> > > ![image](https://private-user-images.githubusercontent.com/38394738/376042971-dd3cec54-69a0-46c3-b783-da36e52710b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNzQzNzIsIm5iZiI6MTcyOTI3NDA3MiwicGF0aCI6Ii8zODM5NDczOC8zNzYwNDI5NzEtZGQzY2VjNTQtNjlhMC00NmMzLWI3ODMtZGEzNmU1MjcxMGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE3NTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0OWM1ZjZkMTExMTViZDIyNjBiYTYzYzlmZTQwYzQ1ZTVjMGZhMDljYzViMDdmNTVkNjVmMzBmYTAxNTc3MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-gbpFKe1XJ5Mnvi0xM-vsCfBDp2Tdyph4HiwqtcGqLY)
> 
> > 
> 
> > 你电脑是放大显示了吗?放大125% or 150%?
> 
> 
> 
> 

好的，那我关闭这个issue了!如果有问题可以继续提交新的issue!
*如果本项目对您有用欢迎start并推荐给需要的人*
